import { subDays } from 'date-fns';

export const mockClientPortal = {
  name: 'רחל מזרחי',
  businessName: 'מסעדת הגליל',
  phone: '052-9876543',
  email: 'rachel@hagalil.co.il',
  address: 'רחוב אלנבי 100, תל אביב',
  area: 'תל אביב',
  debt: 1850,
  creditLimit: 10000,
  rating: 5.0,
};

export const mockClientOrders = [
  {
    id: 'INV-1042',
    date: subDays(new Date(), 1),
    status: 'delivered',
    workerName: 'משה אברהם',
    workerPhone: '052-1112233',
    eta: null,
    deliveredAt: '10:32',
    items: [
      { name: 'שמן זית',    qty: 4, price: 32 },
      { name: 'גבינה לבנה', qty: 4, price: 28 },
      { name: 'סוכר',       qty: 2, price: 12 },
    ],
    total: 296,
    signed: true,
    rating: 5,
  },
  {
    id: 'INV-1038',
    date: subDays(new Date(), 5),
    status: 'delivered',
    workerName: 'נועה ריבלין',
    workerPhone: '053-0001122',
    eta: null,
    deliveredAt: '13:15',
    items: [
      { name: 'שמן זית', qty: 6, price: 32 },
      { name: 'קמח לבן', qty: 3, price: 18 },
    ],
    total: 246,
    signed: true,
    rating: 4,
  },
  {
    id: 'INV-1051',
    date: new Date(),
    status: 'on_the_way',
    workerName: 'משה אברהם',
    workerPhone: '052-1112233',
    eta: '14:30',
    deliveredAt: null,
    workerLat: 32.0853,
    workerLng: 34.7818,
    items: [
      { name: 'שמן זית',    qty: 5, price: 32 },
      { name: 'גבינה לבנה', qty: 6, price: 28 },
    ],
    total: 328,
    signed: false,
    rating: null,
  },
  {
    id: 'INV-1029',
    date: subDays(new Date(), 12),
    status: 'delivered',
    workerName: 'משה אברהם',
    workerPhone: '052-1112233',
    eta: null,
    deliveredAt: '09:50',
    items: [
      { name: 'קמח לבן',   qty: 5, price: 18 },
      { name: 'סוכר',      qty: 4, price: 12 },
      { name: 'שמן זית',   qty: 3, price: 32 },
    ],
    total: 234,
    signed: true,
    rating: 5,
  },
];
